### ISSUE TITLE
Movement Issue

### ISSUE THREAD

**Issue by eagleEggs** [JohannesDeml/adaptingGravityUnity3D#1]
Hey! This is an awesome project. I figured I'd pull it into Unity 2017 and resolve any potential issues. Off the bat, the forward movement is jittery and I was just wondering if the movement was ever fluid in the original build

 I started modifying the code and got it about a half second faster, but it seems there is about a 2 second delay between movements (not rotations). Wanted to check whether it ever was completely responsive :)

The calculations shouldn't be that intensive from what I"m looking at, however the player becomes more responsive when further away from the gravity object :/ May just need to update some functions for the movements and the normal detection etc... If you could let me know I'm going to see if I can get that fixed :D

**Comment by JohannesDeml** [comment]
Hmmm... very good question, as you can see, it has been quite a lot of time since I touched the code. Back then I had way less programming experience (especially with unity specifics). I think it was not superfuild, but also not that jittery (The movement at least, the rotations had some problems).

Sorry for the vague answer, I can't really tell ^^
If I would need an adapting gravity I guess I would take a quick look at this repo, but then program it from scratch again.

**Comment by eagleEggs** [comment]
Haha sounds good. I"ll get it working and maybe add some optimization and submit a pull request to get it updated. Just something to fill the time for now. Closing issue. Thanks :D

**Comment by JohannesDeml** [comment]
I would love a PR, but no pressure ;)

**Comment by eagleEggs** [comment]
Sure np. I see actually the rotation issue. To make it smooth just going forward, the force script needs to be disabled. But while enabled both forward without rot and with rot is jittery.  Obviously that script is needed to keep it rotated up and not wobble off the ground. If you change fixedupdate to update, its smooth. The rotations are always an issue though regardless probably due to recalculating. I noticed when changing some float values in that script it becomes smoother. We’ll see... I am converting to c# and working out these bugs. Overall its very cool when flipping over edges :D Can’t wait until its solid.

**Comment by JohannesDeml** [comment]
Nice, sounds like you're making progress 👍 
Looking forward to the PR
